// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiguelRomeroWeb.Models;

namespace MiguelRomeroWeb.Migrations
{
    [DbContext(typeof(MiguelRomeroWebContext))]
    [Migration("20190224034821_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MiguelRomeroWeb.Models.ClienteInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cuantos");

                    b.Property<string>("Donde");

                    b.Property<string>("Necesidad");

                    b.Property<string>("Nombre");

                    b.Property<string>("TipoEvento");

                    b.HasKey("Id");

                    b.ToTable("ClienteInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
